list_of_fam="smalltest10.txt"
for ref_sys in `cat ${list_of_fam}`; do
mkdir ${ref_sys}
cd ${ref_sys}
for i in {1..35}; do
mkdir anc_${i}
cd anc_${i}
cat >dn_generic.in<<EOF

conformer_search_type                                        denovo
dn_fraglib_scaffold_file                                     /gpfs/projects/rizzo/ccorbo/Testing_Grounds/Layered_FP/fraglib/fraglib_scaffold.mol2
dn_fraglib_linker_file                                       /gpfs/projects/rizzo/ccorbo/Testing_Grounds/Layered_FP/fraglib/fraglib_linker.mol2
dn_fraglib_sidechain_file                                    /gpfs/projects/rizzo/ccorbo/Testing_Grounds/Layered_FP/fraglib/fraglib_sidechain.mol2
dn_user_specified_anchor                                     yes
dn_fraglib_anchor_file                                       /gpfs/projects/rizzo/ccorbo/Testing_Grounds/srun_dn/anchors/anchor_${i}.mol2
dn_torenv_table                                              /gpfs/projects/rizzo/ccorbo/Testing_Grounds/Layered_FP/fraglib/fraglib_torenv.dat
dn_use_roulette                                              no
dn_name_identifier                                           denovo
dn_sampling_method                                           rand
dn_num_random_picks                                          35
dn_pruning_conformer_score_cutoff                            100.0
dn_pruning_conformer_score_scaling_factor                    1.0
dn_pruning_clustering_cutoff                                 100.0
use_dynamic_reference                                        yes
dynamic_ref_filename                                         /gpfs/projects/rizzo/ccorbo/Building_Stuff/DOCK6_with_ambpdb/SB_2020_testset/${ref_sys}/${ref_sys}.lig.am1bcc.mol2
dn_mol_wt_cutoff_type                                        soft
dn_upper_constraint_mol_wt                                   550.0
dn_lower_constraint_mol_wt                                   300.0
dn_mol_wt_std_dev                                            35.0
dn_constraint_rot_bon                                        20
dn_constraint_formal_charge                                  2.0
dn_heur_unmatched_num                                        1
dn_heur_matched_rmsd                                         0.2
dn_unique_anchors                                            1
dn_max_grow_layers                                           9
dn_max_root_size                                             25
dn_max_layer_size                                            25
dn_max_current_aps                                           6
dn_max_scaffolds_per_layer                                   5
dn_write_checkpoints                                         yes
dn_write_prune_dump                                          no
dn_write_orients                                             yes
dn_write_growth_trees                                        yes
dn_output_prefix                                             output
use_internal_energy                                          yes
internal_energy_rep_exp                                      12
internal_energy_cutoff                                       100.0
use_database_filter                                          no
orient_ligand                                                yes
automated_matching                                           yes
receptor_site_file                                           /gpfs/projects/rizzo/ccorbo/Building_Stuff/DOCK6_with_ambpdb/SB_2020_testset/${ref_sys}/${ref_sys}.rec.clust.close.sph
max_orientations                                             1000
critical_points                                              no
chemical_matching                                            no
use_ligand_spheres                                           no
bump_filter                                                  no
score_molecules                                              yes
contact_score_primary                                        no
grid_score_primary                                           no
gist_score_primary                                           no
multigrid_score_primary                                      no
dock3.5_score_primary                                        no
continuous_score_primary                                     no
footprint_similarity_score_primary                           no
pharmacophore_score_primary                                  no
hbond_score_primary                                          no
interal_energy_score_primary                                 no
descriptor_score_primary                                     yes
descriptor_use_grid_score                                    yes
descriptor_use_multigrid_score                               no
descriptor_use_continuous_score                              no
descriptor_use_footprint_similarity                          no
descriptor_use_pharmacophore_score                           no
descriptor_use_tanimoto                                      no
descriptor_use_hungarian                                     yes
descriptor_use_volume_overlap                                no
descriptor_use_gist                                          no
descriptor_use_dock3.5                                       no
descriptor_grid_score_rep_rad_scale                          1
descriptor_grid_score_vdw_scale                              1
descriptor_grid_score_es_scale                               1
descriptor_grid_score_grid_prefix                            /gpfs/projects/rizzo/ccorbo/Building_Stuff/DOCK6_with_ambpdb/SB_2020_testset/${ref_sys}/${ref_sys}.rec
descriptor_hms_score_ref_filename                            /gpfs/projects/rizzo/ccorbo/Building_Stuff/DOCK6_with_ambpdb/SB_2020_testset/${ref_sys}/${ref_sys}.lig.am1bcc.mol2
descriptor_hms_score_matching_coeff                          -5
descriptor_hms_score_rmsd_coeff                              1
descriptor_weight_grid_score                                 1
descriptor_weight_hms_score                                  25
minimize_ligand                                              yes
minimize_anchor                                              yes
minimize_flexible_growth                                     yes
use_advanced_simplex_parameters                              no
simplex_max_cycles                                           1
simplex_score_converge                                       0.1
simplex_cycle_converge                                       1.0
simplex_trans_step                                           0.25
simplex_rot_step                                             0.1
simplex_tors_step                                            15.0
simplex_anchor_max_iterations                                500
simplex_grow_max_iterations                                  250
simplex_grow_tors_premin_iterations                          0
simplex_random_seed                                          0
simplex_restraint_min                                        no
atom_model                                                   all
vdw_defn_file                                                /gpfs/projects/rizzo/ccorbo/Testing_Grounds/Layered_FP/21_12_18_AnchorTestingSecMin/vdw_AMBER_parm99.defn
flex_defn_file                                               /gpfs/projects/rizzo/zzz.programs/dock6.9_mpiv2018.0.3/parameters/flex.defn
flex_drive_file                                              /gpfs/projects/rizzo/zzz.programs/dock6.9_mpiv2018.0.3/parameters/flex_drive.tbl
EOF

cd ../
done
cd ../
done
